GET http://localhost:5242/games

###
GET http://localhost:5242/games/50

###
POST http://localhost:5242/games
Content-Type: application/json

{
    "name": "Dota 2",
    "genre": "MMORPG",
    "price": "0",
    "releaseDate": "2015-10-20"
}

###
PUT http://localhost:5242/games/10
Content-Type: application/json

{
    "name": "Street Fighter",
    "genre": "Fighting",
    "price": 5.99,
    "releaseDate": "1992-07-15"
}

###
DELETE http://localhost:5242/games/10 